# https://discourse.mc-stan.org/t/rstan-rstantools-travis/6102
language: r
sudo: true
cache: packages

env:
  global:
    - ALLOWED_NOTES=1
    - NO_IMPORTS=0

r_binary_packages:
  - devtools
  - rstan

notifications:
  email:
    recipients:
     - alerts+travis@jumpingrivers.support
    on_success: change
    on_failure: change

before_install:
  - sudo apt-get install -y python3 python3-pip
  - sudo apt-get install -y ghostscript
  - pip3 install pygments

before_script:
  - wget https://raw.githubusercontent.com/jr-packages/drat/master/test_deploy.sh
  - bash test_deploy.sh && rm test_deploy.sh

script:
  - Rscript -e "source('https://raw.githubusercontent.com/jr-packages/drat/master/script.R')"

after_success:
  - wget https://raw.githubusercontent.com/jr-packages/drat/master/deploy.sh
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
